repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff lint (fix)
        entry: ruff
        args: ["check", "--fix"]
        language: system
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: ruff
        args: ["format"]
        language: system
        types: [python]

      - id: whitespace-fixer
        name: whitespace fixer (all files)
        entry: scripts/hooks/whitespace_fixer.sh
        language: system
        files: ".*"

      - id: check-merge-conflict
        name: check merge conflicts (all files)
        entry: scripts/hooks/check_merge_conflict.sh
        language: system
        files: ".*"
